[WIP] Cryptorf
RfidResearchGroup/proxmark3 pull request #639
Opened 2020-04-03 19:20 UTC by baloncu

Added support for CryptoRF tag simulation. 
Crypto engine implementation is from the topic below. 
http://www.proxmark.org/forum/viewtopic.php?id=4855

Tested the implementation for a cryptoRF tag (AT88SC6416CRF).

Tag memory is generated as a header file, to change the tag memory, one need to change tag_mem.h
Many performance optimizations are implemented for tag response generation and crypto engine. 
Used lookup tables instead of calculations where possible.
Main changes are in the armsrc iso14443b.c file.

2020-04-03 19:58 UTC, iceman1001 commented
Looks like an awesome addition!.

How is the ram memory usage?,  there is some pretty large LUTs you are using.
and the changes into arm-side 14b,   does that make 14b more stable aswell or just CryptoRF?

And you should run ```make style```  in order to get the code adapted to our prefered code style.
and don't forget a line in the CHANGELOG.md file!

2020-04-03 19:59 UTC, iceman1001 commented
Appveyour is confirming the RAM part...

![image](https://user-images.githubusercontent.com/8577004/78400112-6380a000-75f6-11ea-9601-a4ab2c651bb6.png)

2020-04-03 20:11 UTC, baloncu commented
> Appveyour is confirming the RAM part...
> 
> ![image](https://user-images.githubusercontent.com/8577004/78400112-6380a000-75f6-11ea-9601-a4ab2c651bb6.png)

interesting. I did build it as well and didn't get a complaint about the ram size. I used PM3OTHER platform setting though as I have an RDV2

2020-04-03 21:57 UTC, baloncu commented
I have changed the size of the tag memoryto solve the RAM issue. Now it is simulating a ATSC1616CRF tag. My changes are for cryptorf. I only added a TR1 synchronization timing for the rest of the hf 14b code. I did 'make style' and add a line in changelog. But I am having a conflict in changelog.md

2020-04-04 04:55 UTC, iceman1001 commented
Why are you hard coding a tag?   Why not use the reserved space called "emulator" memory of the bigbuffer?   You can have "eload/esave" commands in client to upload/download  the tag you want to simulate.  That will save some space. 

Next thing we will need is  a way to read -> dump a cryptoRF tag's memory. In order to create the files needed for simulation.

2020-04-04 10:21 UTC, iceman1001 commented
And now you will have some conflicts.  Not that hard to sort out,  pm3_cmd.h  *sry*

2020-04-05 07:30 UTC, iceman1001 commented
Are you on signal?  or email?

2020-04-05 15:27 UTC, baloncu commented
I am getting emails. I am not on signal.

2020-04-05 15:34 UTC, baloncu commented
> Great!
> 
> Awesome stuff bro,   
> 
> now some questions,  why are you hard coding a tag?   Why not use the reserved space called "emulator" memory of the bigbuffer?   You can have "eload/esave" commands in client to upload/download  the tag you want to simulate.  That will save some space. 
> 
> 
> 
> Next thing we will need is  a way to read -> dump a cryptoRF tag's memory. In order to create the files needed for simulation.

I am using a hard coded file, I didn’t realize the eload/esave use. It was a quick and easy way of doing it. I will look into that to see if I can use the client to load a memory image.

For reading a tag, the reader code didn’t work reliably enough for me to read many bytes back to back. I tried to fix it but it wasn’t good enough to read many bytes. I am not confident about reading tag memory in a loop.

2020-04-05 15:35 UTC, baloncu commented
> And now you will have some conflicts.  Not that hard to sort out,  pm3_cmd.h  *sry*

I will fix these but I can only look at this tomorrow. Thanks.

2020-04-05 16:11 UTC, iceman1001 commented
lets see then,  we could merge,  and rearrange stuff..

We would need info/read/write/dump all/ eload/esave to nice support for CryptoRF. 
I also think it should have its own command group, direct under **hf cryptorf** instead for under 14b.   Even if its 14b based,  think like iClass which can be both 14b and 15693 based.

2020-04-05 16:11 UTC, iceman1001 commented
With that we would have almost full support for cryptoRF  !

2020-04-05 19:28 UTC, baloncu commented
Makes sense, i can rearrange the code like iclass.

2020-04-06 04:21 UTC, iceman1001 commented
ok, to help you out, I pushed two new files,  a skeleton for cryptorf commands.  
It compiles and uncomment one line in cmdhf.c and you can test your stuff direct.
its based on the 14b cmds,  so it shouldn't be too hard to mix in your stuff :)

2020-04-06 22:40 UTC, baloncu commented
> ok, to help you out, I pushed two new files, a skeleton for cryptorf commands.
> It compiles and uncomment one line in cmdhf.c and you can test your stuff direct.
> its based on the 14b cmds, so it shouldn't be too hard to mix in your stuff :)

Okay, I got the skeleton you added and now working on it. But you are fast :) - I hope you are not expecting such fast coding skills from me. 

Btw, I added a new CRYPTORF simulate command in the armsrc/appmain.c, that is what I plan to use. Also for the dump/read etc. there is some code in get_14b_UID that checks if the tag is SRx first. I don't think those are necessary when we are using a tag we know cryptorf.

2020-04-07 07:13 UTC, iceman1001 commented on include/pm3_cmd.h
> +#define CMD_HF_ISO14443B_SIM_CRYPTORF                                     0x0812
In order to keep things a bit clear,  lets follow the nomenclature:
CMD_HF_CRYPTORF_SIM
---------------------xxxxx
where xxxx will be the implemented command for cryptoRF.

2020-04-07 07:15 UTC, iceman1001 commented
The skeleton was taken from 14B source,  so it still has residue from things that isn't needed for cryptoRF.   Also why it went fast to do ;)

Its easier to chat, instead of having the conv here.   I can help to get things speeded up,  if you want it.

2020-04-21 19:30 UTC, doegox commented
Where are we on this one @baloncu ?

2020-04-21 19:59 UTC, baloncu commented
> Where are we on this one @baloncu ?

sorry guys! I didn't have much time to look at this recently. My implementation of the tag simulation depends on a hardcoded tag file. I was hoping to get rid of the tag_mem.h and instead take it as a parameter for eload command and utilize the card memory allocated in big buffer. I can take a look at this by the weekend and commit my changes.

2020-04-21 20:30 UTC, doegox commented
no urgency :) I was just curious

2020-04-26 23:25 UTC, baloncu commented
Hi guys,
My desired changes require me to test the code on the hardware and I am not able to do that. However the code as it is right now can do CryptoRF simulation (not very elegant, we still read the tag memory from a header) and does other 14B commands (no changes to the standard code except 3 retries for Info command). What we can do is to close/reject this PR and I can open another one if/once I have access to my hardware and can test my code or we can integrate as it is. I prefer not to push any changes that are not tested on HW.

2020-04-27 08:12 UTC, doegox commented
>  I prefer not to push any changes that are not tested on HW.

Sure, we respect that.
We can leave the PR open to keep track of the comments, no problem. I tagged it as [WIP].

2020-04-27 16:55 UTC, baloncu commented
Great! Thanks.

2021-12-12 15:14 UTC, marceloadryao requested changes
> Added support for CryptoRF tag simulation. 
Crypto engine implementation is from the topic below. 
http://www.proxmark.org/forum/viewtopic.php?id=4855

Tested the implementation for a cryptoRF tag (AT88SC6416CRF).

Tag memory is generated as a header file, to change the tag memory, one need to change tag_mem.h
Many performance optimizations are implemented for tag response generation and crypto engine. 
Used lookup tables instead of calculations where possible.
Main changes are in the armsrc iso14443b.c file.

2022-05-08 21:32 UTC, kabiri commented
Does this work with the at88rf04c tag?
Can anyone help me how to decode the string I read from the tag?

Key Index = 12 Session Encryption Key S2 , Q1-8 = 9C31E4A9352EB6EB , CH1-8 = B492F00A7CEA4C0F
Data is : 58BC6E20EB1A9EE483A9FD008843AB14

2023-06-07 20:58 UTC, team-orangeBlue commented
Is this PR still up and alive? 3 years, still open.

2023-06-07 23:36 UTC, baloncu commented
I will close this one as I have no free time to work on it. If/Once I do have sometime, I will work on the changes and open a new PR.

2023-06-07 23:36 UTC, closed without merging

2023-06-08 06:10 UTC, iceman1001 commented
No need to close.  The [WIP] tag was added in order to keep it alive and not loose track of the source code. 

Just that there was no time and HW to test the needed changes.